server:
  port: 9090

spring:
  boot:
    admin:
      client:
        #──────────────────────────────────────────────────────────────────────────────────────────
        # Spring-Admin URL 설정. 일반 배포 시 설정
        #──────────────────────────────────────────────────────────────────────────────────────────
        url: http://localhost:8080
        #──────────────────────────────────────────────────────────────────────────────────────────
        # SPRING-SECURITY 설정
        #──────────────────────────────────────────────────────────────────────────────────────────
        instance:
          #──────────────────────────────────────────────────────────────────────────────────────────
          # Spring-Admin URL 설정. war 배포 시 설정
          #──────────────────────────────────────────────────────────────────────────────────────────
#          service-url: http://localhost:8080
          #──────────────────────────────────────────────────────────────────────────────────────────
          # Spring-Admin 모니터링 Application 이름 설정
          #──────────────────────────────────────────────────────────────────────────────────────────
          name: "SPRING-ADMIN-CLIENT"

#──────────────────────────────────────────────────────────────────────────────────────────
# Spring Admin 의 경우 Actuator end-point 사용하여 프로세스 상태를 확인하며 '*'는 전체 노출을 의미함
#──────────────────────────────────────────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#──────────────────────────────────────────────────────────────────────────────────────────
# logback 환경 설정 파일 위치 설정
#──────────────────────────────────────────────────────────────────────────────────────────
logging:
  config:
    classpath:logback-spring.xml
  #──────────────────────────────────────────────────────────────────────────────────────────
  # logback 로그 파일 위치 설정
  #──────────────────────────────────────────────────────────────────────────────────────────
  file:
    name: C:\git-repository\spring-admin-client1\logs\logback_test.log